- name: add nginx user
  become: true
  user:
    name: nginx

- name: install nginx
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: start nginx
  become: true
  service:
    name: nginx
    enabled: yes