name: Run playbook
on: [push, pull_request]

jobs:
  test-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Local
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./test/defaults
          options: |
            --inventory hosts  
            --limit local  